### ISSUE TITLE
PapaAE2 won't launch

### ISSUE THREAD

**Issue by benjapo-pixel** [RSAnimation/Papagayo#1]
Hello there!

Papagayo runs great on Sierra, but unfortunately PapaAE2 won't launch. I know this is a very old project, but I wanted to reach out just in case it would be possible to update PapaAE2 to run.

If not, no worries. Thank you for updating this for as long as you did. I've really enjoyed using it! 👍 

Cheers,
Ben

**Comment by benjapo-pixel** [comment]
Nevermind, I'm an idiot. I found the nested ZIP file that contains PapaAE5c and it works!!
I'm good now. Sorry for the false alarm!!

**Comment by RSAnimation** [comment]
I have a newer update for papaAE that uses sliders for the mouthshapes instead of time remapping. You have to have the newest versions of After Effects and Duik for it to work though. Let me know if you want me to up it. There are not very many people who use it so I didn't bother to update the github.

**Comment by benjapo-pixel** [comment]
Yeah I'm game for trying it out. Unsure if/when I can test the new
features. But if I'm able to provide any useful feedback I'll let you know!
